name: CI/CD Vue + Node

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test || echo "No tests found"

    - name: Build del frontend (Vue)
      run: npm run build

    - name: Ver contenido generado
      run: ls dist

    - name: Deploy a GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist